name: Infracost Analysis of Ephemeral Envrioment
on:
  push:
    branches:
      - main
jobs:
  get-cost-analysis:
    runs-on: ubuntu-latest
    env:
        TF_DIR: ./IaC
        TF_ENV: dev   
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: cost-analysis-with-infracost
        run: |
          infracost breakdown --path $TF_DIR \
                    --format json \
                    --terraform-var-file $TF_DIR/$TF_ENV.tfvars \
                    --terraform-var app_version=${{ github.sha }} \
                    --out-file cost-analysis.json

          jq . cost-analysis.json
          jq '.totalResources' cost-analysis.json
          jq '.projects[] | .breakdown.resources[] | {name: .name, hourlyCost: .hourlyCost, monthlyCost: .monthlyCost}' cost-analysis.json
          jq '.projects[] | .metadata | .warnings, .errors' cost-analysis.json

      #     TOTAL_HOURLY_COST=$(jq '[.projects[] | .breakdown.resources[] | .hourlyCost | tonumber] | add' cost-analysis.json)
      #     TOTAL_DAILY_COST=$(echo "$TOTAL_HOURLY_COST * 24" | bc)
      #     TOTAL_RESOURCES=$(jq '.totalDetectedResources' cost-analysis.json)
      #     COST_SUMMARY="Total Daily Cost: $TOTAL_DAILY_COST, Total Resources Detected: $TOTAL_RESOURCES"
      #     echo "COST_SUMMARY=$COST_SUMMARY" >> $GITHUB_ENV
    
      # - name: echo-cost-summary
      #   run: |
      #     echo $COST_SUMMARY


            
          
    

        
          


