name: Infracost Analysis of Ephemeral Envrioment
on: push
jobs:
  verify-branch-name:
    runs-on: ubuntu-latest
    outputs:
      is_valid: ${{ steps.check_branch_name.outputs.is_valid }}
    steps:
        - name: verify-branch-name
          id: check_branch_name
          run: |
            if [[ "${{ github.ref_name }}" =~ ^[A-Z]{3,7}-[0-9]{1,5}$ ]]; then
              echo "Branch name is valid."
              echo "is_valid=true" >> $GITHUB_OUTPUT
            else
              echo "Invalid branch name. The branch name must correspond to a Jira issue key."
              echo "is_valid=false" >> $GITHUB_OUTPUT
            fi
  get-cost-analysis:
    runs-on: ubuntu-latest
    needs: verify-branch-name
    if: ${{ needs.verify-branch-name.outputs.is_valid == 'true' }}
    env:
        TF_DIR: ./IaC
        TF_ENV: dev   
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: cost-analysis-with-infracost
        run: |
          infracost breakdown --path $TF_DIR \
            --format json \
            --terraform-var-file $TF_ENV.tfvars \
            --terraform-var app_version=${{ github.sha }} \
            --out-file cost-analysis.json
          TOTAL_HOURLY_COST=$(jq '[.projects[] | .breakdown.resources[] | .hourlyCost | tonumber] | add' cost-analysis.json)
          TOTAL_DAILY_COST=$(echo "$TOTAL_HOURLY_COST * 24" | bc)
          TOTAL_RESOURCES=$(jq '.summary.totalDetectedResources' cost-analysis.json)
          COST_SUMMARY="Total Daily Cost: $TOTAL_DAILY_COST, Total Resources Detected: $TOTAL_RESOURCES"
          echo "COST_SUMMARY=$COST_SUMMARY" >> $GITHUB_ENV
    
      - name: echo-cost-summary
        run: |
          echo $COST_SUMMARY


            
          
    

        
          


