name: Build
on:
  push:
    branches:
      - main # the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build-and-test # will probably have to setup java first
        run: |
          mvn clean package
      # - name: scan-maven-with-sonar-clound
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     projectBaseDir: ./microservice/
      #     args: >
      #       -Dsonar.projectKey=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2) # projecct key is the name of the repository
      #       -Dsonar.organization="mehrdad-ordobadi" # check if the value is correct
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      #       -Dsonar.host.url=https://sonarcloud.io
      - name: Scan Maven project with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG_KEY: mehrdad-ordobadi
          SONAR_PROJECT_KEY: ${{ github.repository }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ env.SONAR_ORG_KEY }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ env.SONAR_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t my-application:${{ github.sha }} .
          
      - name: Push Docker image to registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $GITHUB_REPOSITORY:${{ github.sha }}

